#! /bin/bash

# assumes a directory named "output",
# located parallel to src directory

# make "output" the working directory and
# call this script as ../script/make-tex

cp -a ../styles/structured-latex.sty .
cp -a ../src/images/graphplot.png .

cp -a ../src/LmacsB.tex .
cp -a ../src/Practice.tex .
cp -a ../src/preface.tex .
cp -a ../src/basics.tex .
cp -a ../src/projects.tex .
cp -a ../src/cayley.tex .
cp -a ../src/drgs.tex .
cp -a ../src/pseries.tex .
cp -a ../src/matrices.tex .
cp -a ../src/fdl-1.3.tex .

pdflatex Practice.tex