#! /bin/bash

# assumes a directory named "output",
# located parallel to src directory

# make "output" the working directory and
# call this script as ../script/make-html

# ./index.html will be main table of contents

# create Docbook XML files
sed -f ../script/structured-latex.sed ../src/preface.tex > ./preface.xml
sed -f ../script/structured-latex.sed ../src/basics.tex > ./basics.xml
sed -f ../script/structured-latex.sed ../src/projects.tex > ./projects.xml
sed -f ../script/structured-latex.sed ../src/cayley.tex > ./cayley.xml
sed -f ../script/structured-latex.sed ../src/drgs.tex > ./drgs.xml
sed -f ../script/structured-latex.sed ../src/pseries.tex > ./pseries.xml
sed -f ../script/structured-latex.sed ../src/matrices.tex > ./matrices.xml

# run XSLT processor
cp -a ../src/practice.xml .
cp -a ../src/fdl-1.3.xml .
cp -a ../src/knowls/cubelike.html .
cp -a ../styles/docbook-free-bsd-sage.css .
xsltproc --xinclude --stringparam html.stylesheet "docbook-free-bsd-sage.css" --stringparam use.id.as.filename 1 --stringparam chunker.output.encoding UTF-8 ../xsl/math-sage.xsl practice.xml

